//! Renders `tests/generated_fixtures.rs` from the crate's own fixture corpus.
//!
//! Nothing here runs in the browser: the module is compiled out on wasm.

use std::path::PathBuf;

use crate::{convert, ConvertError, Options};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FixtureKind {
    /// `{"blocks": [...]}`
    Message,
    /// One `SlackBlock` object.
    Block,
    /// An untagged home view; the `"type"` tag is supplied before conversion.
    HomeView,
}

/// Every file in the corpus and how to read it. A fixture added without a
/// line here fails `every_fixture_on_disk_is_classified`.
pub const FIXTURE_KINDS: &[(&str, FixtureKind)] = &[
    ("slack_alert_block.json", FixtureKind::Block),
    ("slack_card_block.json", FixtureKind::Block),
    ("slack_context_actions_block.json", FixtureKind::Block),
    (
        "slack_conversations_select_with_filter.json",
        FixtureKind::Block,
    ),
    ("slack_home_view.json", FixtureKind::HomeView),
    ("slack_image_blocks.json", FixtureKind::Message),
    ("slack_rich_text_block.json", FixtureKind::Block),
    ("slack_table_block.json", FixtureKind::Block),
    ("slack_task_card_block.json", FixtureKind::Block),
    ("slack_workflow_button.json", FixtureKind::Block),
];

/// Fixtures whose shapes no visitor hand-builds yet, tagged with the emitter
/// area that will take them. An entry is deleted when its visitors land, so the
/// array is empty once every block, element and view has a hand-written visitor.
pub const SKIPPED_FIXTURES: &[(&str, &str)] = &[
    ("slack_alert_block.json", "tables"),
    ("slack_card_block.json", "tables"),
    ("slack_context_actions_block.json", "tables"),
    ("slack_conversations_select_with_filter.json", "elements"),
    ("slack_home_view.json", "views"),
    ("slack_rich_text_block.json", "rich_text"),
    ("slack_table_block.json", "tables"),
    ("slack_task_card_block.json", "tables"),
    ("slack_workflow_button.json", "elements"),
];

pub fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../src/models/blocks/fixtures")
}

pub fn generated_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/generated_fixtures.rs")
}

const HEADER_DOC: &str = "\
//! Generated by `bk2rs --regen-fixtures`. Do not edit by hand.
//!
//! Each test rebuilds one fixture with the emitted builder code and asserts
//! that the result serializes to the value the crate parsed from the fixture.
//! A test that fails to compile is an emitter bug in the open.
";

/// Covered fixtures name the same handful of `parse_*` helpers, and
/// `SKIPPED_FIXTURES` can leave a whole `FixtureKind` with nothing covered —
/// generated code is not exempt from clippy, so an unused import here would
/// fail the gate as surely as one in hand-written code.
pub fn render_generated_fixtures() -> Result<String, ConvertError> {
    let covered: Vec<(&str, FixtureKind)> = FIXTURE_KINDS
        .iter()
        .copied()
        .filter(|(name, _)| !SKIPPED_FIXTURES.iter().any(|(n, _)| n == name))
        .collect();

    let mut helpers = vec!["assert_same", "Normalize"];
    if covered.iter().any(|(_, k)| *k == FixtureKind::Message) {
        helpers.push("parse_blocks");
    }
    if covered.iter().any(|(_, k)| *k == FixtureKind::Block) {
        helpers.push("parse_block");
    }
    if covered.iter().any(|(_, k)| *k == FixtureKind::HomeView) {
        helpers.push("as_home_view");
    }
    // rustfmt reorders a `use` list itself, snake_case names alphabetically
    // before PascalCase ones; matching that order here up front is what
    // keeps a freshly generated file identical after `cargo fmt` runs on it.
    helpers
        .sort_unstable_by_key(|name| (name.chars().next().is_some_and(char::is_uppercase), *name));

    let mut out = format!(
        "{HEADER_DOC}\nuse blockkit_to_rust::testkit::{{{}}};\n",
        helpers.join(", ")
    );
    for (name, kind) in covered {
        for exact in [false, true] {
            out.push('\n');
            out.push_str(&render_one(name, kind, exact)?);
        }
    }
    Ok(out)
}

fn render_one(name: &str, kind: FixtureKind, exact: bool) -> Result<String, ConvertError> {
    let path = fixtures_dir().join(name);
    let source = std::fs::read_to_string(&path).map_err(|e| ConvertError::Json {
        message: format!("{}: {e}", path.display()),
    })?;
    let source = match kind {
        FixtureKind::HomeView => {
            crate::testkit::tagged_home_view(&source).map_err(|e| ConvertError::Json {
                message: e.to_string(),
            })?
        }
        _ => source,
    };

    let options = Options {
        emoji_true_is_default: !exact,
        ..Options::default()
    };
    let converted = convert(&source, &options)?;

    let stem = name.trim_end_matches(".json");
    let suffix = if exact { "exact" } else { "default" };
    let normalize = if exact {
        "Normalize::Exact"
    } else {
        "Normalize::StripEmojiTrue"
    };
    let (binding, parse_call) = match kind {
        FixtureKind::Message => ("blocks", "parse_blocks(FIXTURE)?"),
        FixtureKind::Block => ("block", "parse_block(FIXTURE)?"),
        FixtureKind::HomeView => ("view", "as_home_view(FIXTURE)?"),
    };

    let body = converted
        .code
        .lines()
        .map(|l| {
            if l.is_empty() {
                String::from("\n")
            } else {
                format!("    {l}\n")
            }
        })
        .collect::<String>();

    Ok(format!(
        "#[rustfmt::skip]\n\
         #[test]\n\
         fn {stem}_{suffix}() -> Result<(), Box<dyn std::error::Error>> {{\n\
         {body}\
         \n    \
         const FIXTURE: &str = include_str!(\"../../../src/models/blocks/fixtures/{name}\");\n    \
         assert_same(&{binding}, &{parse_call}, {normalize})?;\n    \
         Ok(())\n\
         }}\n"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_fixture_on_disk_is_classified() {
        let mut on_disk: Vec<String> = std::fs::read_dir(fixtures_dir())
            .expect("fixtures dir")
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n.ends_with(".json"))
            .collect();
        on_disk.sort();
        let mut known: Vec<String> = FIXTURE_KINDS
            .iter()
            .map(|(n, _)| (*n).to_string())
            .collect();
        known.sort();
        assert_eq!(on_disk, known, "add the new fixture to FIXTURE_KINDS");
        assert_eq!(on_disk.len(), 10);
    }

    #[test]
    fn the_renderer_emits_two_tests_per_covered_fixture() {
        let rendered = render_generated_fixtures().expect("renders");
        let covered = FIXTURE_KINDS.len() - SKIPPED_FIXTURES.len();
        assert_eq!(rendered.matches("#[test]").count(), covered * 2);
        assert!(rendered.contains("fn slack_image_blocks_default()"));
        assert!(rendered.contains("fn slack_image_blocks_exact()"));
    }

    #[test]
    fn skipped_fixtures_name_an_emitter_area_that_will_take_them() {
        for (name, owner) in SKIPPED_FIXTURES {
            assert!(
                ["elements", "rich_text", "tables", "views"].contains(owner),
                "{name} is skipped for unknown emitter area {owner}"
            );
            assert!(
                FIXTURE_KINDS.iter().any(|(n, _)| n == name),
                "{name} is not a fixture"
            );
        }
    }
}
