use slack_morphism::prelude::*;

use url::Url;

/// One instance of every block family, spread into a single `slack_blocks!`
/// list so the whole catalogue posts as one message. `show_alert` demonstrates
/// `optionally(pred => item)`; the trailing footer lines demonstrate `..iter`.
fn catalogue_blocks(show_alert: bool) -> Vec<SlackBlock> {
    slack_blocks![
        SlackHeaderBlock::new(pt!("Block Kit showcase")),
        SlackSectionBlock::new()
            .with_text(md!("A single message demonstrating every block family."))
            .with_fields(vec![md!("*Status*\nReady"), md!("*Owner*\nslack-morphism"),])
            .with_accessory(
                SlackBlockButtonElement::new("showcase-more-info".into(), pt!("More info"))
                    .into()
            ),
        SlackImageBlock::new(
            Url::parse("https://www.gstatic.com/webp/gallery3/2_webp_ll.png")
                .expect("a hard-coded, valid URL literal")
                .into(),
            "A sample image".into(),
        ),
        SlackContextBlock::new(vec![md!("Rendered by the `blocks_showcase` example")]),
        SlackActionsBlock::new(slack_blocks![
            SlackBlockButtonElement::new("showcase-button".into(), pt!("Click me")),
            SlackBlockStaticSelectElement::new("showcase-select".into())
                .with_placeholder(pt!("Pick one"))
                .with_options(vec![
                    SlackBlockChoiceItem::new(pt!("Option A"), "a".into()),
                    SlackBlockChoiceItem::new(pt!("Option B"), "b".into()),
                ]),
        ]),
        SlackDividerBlock::new(),
        SlackRichTextBlock::new(vec![
            SlackRichTextSection::new(vec![
                SlackRichTextText::new("Rich text: ".into()).bold().into(),
                SlackRichTextEmoji::new("sparkles".into()).into(),
            ])
            .into(),
            SlackRichTextList::new(
                SlackRichTextListStyle::Bullet,
                vec!["Header".into(), "Section".into(), "Rich text".into()]
            )
            .into(),
            SlackRichTextQuote::new(vec!["Every family, one message.".into()]).into(),
            SlackRichTextPreformatted::new(vec!["cargo run --example blocks_showcase".into()])
                .into(),
        ]),
        SlackTableBlock::new(vec![
            vec!["Family".into(), "Kind".into()],
            vec!["Header".into(), "block".into()],
        ]),
        SlackMarkdownBlock::new("**Markdown block** rendered with native Slack markdown.".into()),
        optionally(show_alert => SlackAlertBlock::new(md!("This is an alert block."))
            .with_level(SlackAlertLevel::Info)),
        SlackCardBlock::new()
            .with_title(md!("slack-morphism"))
            .with_body(md!("A modern Rust client for Slack.")),
        SlackTaskCardBlock::new("showcase-task".into(), "Publish the showcase".into())
            .with_status(SlackTaskCardStatus::Complete),
        ..[
            "This message was generated by the `blocks_showcase` example.",
            "Source: examples/blocks_showcase.rs",
        ]
        .iter()
        .copied()
        .map(|line| SlackBlock::Context(SlackContextBlock::new(vec![md!(line)]))),
    ]
}

/// Opening this view for real needs a trigger id from an interaction payload,
/// which this standalone example does not have; it is printed instead so it
/// can be pasted into Block Kit Builder.
fn feedback_modal() -> SlackView {
    SlackView::Modal(
        SlackModalView::new(
            pt!("Share feedback"),
            slack_blocks![
                SlackInputBlock::new(
                    pt!("What went well?"),
                    SlackBlockPlainTextInputElement::new("feedback-good".into())
                        .with_multiline(true)
                        .into(),
                ),
                SlackInputBlock::new(
                    pt!("Priority"),
                    SlackBlockStaticSelectElement::new("feedback-priority".into())
                        .with_options(vec![
                            SlackBlockChoiceItem::new(pt!("Low"), "low".into()),
                            SlackBlockChoiceItem::new(pt!("High"), "high".into()),
                        ])
                        .into(),
                ),
                SlackInputBlock::new(
                    pt!("Notify"),
                    SlackBlockCheckboxesElement::new(
                        "feedback-notify".into(),
                        vec![SlackBlockChoiceItem::new(
                            pt!("Email me when this is triaged"),
                            "notify".into()
                        )]
                    )
                    .into(),
                ),
            ],
        )
        .with_submit(pt!("Send")),
    )
}

pub fn config_env_var(name: &str) -> Result<String, String> {
    std::env::var(name).map_err(|e| format!("{}: {}", name, e))
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let subscriber = tracing_subscriber::fmt()
        .with_env_filter("slack_morphism=debug")
        .finish();
    tracing::subscriber::set_global_default(subscriber)?;

    let client = SlackClient::new(SlackClientHyperConnector::new()?);
    let token_value: SlackApiTokenValue = config_env_var("SLACK_TEST_TOKEN")?.into();
    let token: SlackApiToken = SlackApiToken::new(token_value);
    let session = client.open_session(&token);

    let channel: SlackChannelId = config_env_var("SLACK_TEST_CHANNEL")?.into();

    let post_chat_req = SlackApiChatPostMessageRequest::new(
        channel,
        SlackMessageContent::new()
            .with_text("Block Kit showcase".into())
            .with_blocks(catalogue_blocks(true)),
    );

    let post_chat_resp = session.chat_post_message(&post_chat_req).await?;
    println!("posted showcase message: {:#?}", post_chat_resp);

    println!(
        "{}",
        serde_json::to_string_pretty(&feedback_modal())
            .expect("SlackView is a plain data structure and always serializes")
    );

    Ok(())
}
