//! Generated by `bk2rs --regen-fixtures`. Do not edit by hand.
//!
//! Each test rebuilds one fixture with the emitted builder code and asserts
//! that the result serializes to the value the crate parsed from the fixture.
//! A test that fails to compile is an emitter bug in the open.

use blockkit_to_rust::testkit::{assert_same, parse_blocks, Normalize};

#[rustfmt::skip]
#[test]
fn slack_image_blocks_default() -> Result<(), Box<dyn std::error::Error>> {
    use slack_morphism::prelude::*;
    use url::Url;

    // `url` must be a dependency of your crate; slack-morphism uses url 2.
    // This snippet uses `?`, so place it in a function returning `Result`.
    let blocks: Vec<SlackBlock> = slack_blocks![
        SlackSectionBlock::new()
            .with_text(md!("*Farmhouse Cuisine*\n:star::star::star::star: 1528 reviews\n They do have some vegan options, like the roti and curry, plus they have a ton of salad stuff and noodles can be ordered without meat!! They have something for everyone here"))
            .with_accessory(SlackBlockImageElement::new(
                Url::parse("https://s3-media3.fl.yelpcdn.com/bphoto/c7ed05m9lC2EmA3Aruue7A/o.jpg")?.into(),
                "alt text for image".into(),
            ).into()),
        SlackImageBlock::new(
            Url::parse("https://assets3.thrillist.com/v1/image/1682388/size/tl-horizontal_main.jpg")?.into(),
            "not so delicious tacos".into(),
        )
        .with_title(pt!("I don't love tacos")),
        SlackImageBlock::new(
            SlackImageUrlOrFile::SlackFile {
                slack_file: SlackFileIdOrUrl::Id { id: "F00000000".into() },
            },
            "delicious tacos".into(),
        )
        .with_title(pt!("I love tacos")),
    ];

    const FIXTURE: &str = include_str!("../../../src/models/blocks/fixtures/slack_image_blocks.json");
    assert_same(&blocks, &parse_blocks(FIXTURE)?, Normalize::StripEmojiTrue)?;
    Ok(())
}

#[rustfmt::skip]
#[test]
fn slack_image_blocks_exact() -> Result<(), Box<dyn std::error::Error>> {
    use slack_morphism::prelude::*;
    use url::Url;

    // `url` must be a dependency of your crate; slack-morphism uses url 2.
    // This snippet uses `?`, so place it in a function returning `Result`.
    let blocks: Vec<SlackBlock> = slack_blocks![
        SlackSectionBlock::new()
            .with_text(md!("*Farmhouse Cuisine*\n:star::star::star::star: 1528 reviews\n They do have some vegan options, like the roti and curry, plus they have a ton of salad stuff and noodles can be ordered without meat!! They have something for everyone here"))
            .with_accessory(SlackBlockImageElement::new(
                Url::parse("https://s3-media3.fl.yelpcdn.com/bphoto/c7ed05m9lC2EmA3Aruue7A/o.jpg")?.into(),
                "alt text for image".into(),
            ).into()),
        SlackImageBlock::new(
            Url::parse("https://assets3.thrillist.com/v1/image/1682388/size/tl-horizontal_main.jpg")?.into(),
            "not so delicious tacos".into(),
        )
        .with_title(SlackBlockPlainText::new("I don't love tacos".into()).with_emoji(true).into()),
        SlackImageBlock::new(
            SlackImageUrlOrFile::SlackFile {
                slack_file: SlackFileIdOrUrl::Id { id: "F00000000".into() },
            },
            "delicious tacos".into(),
        )
        .with_title(SlackBlockPlainText::new("I love tacos".into()).with_emoji(true).into()),
    ];

    const FIXTURE: &str = include_str!("../../../src/models/blocks/fixtures/slack_image_blocks.json");
    assert_same(&blocks, &parse_blocks(FIXTURE)?, Normalize::Exact)?;
    Ok(())
}
