name: tests & formatting
on: 
  push:
  pull_request:
    types: [opened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt -- --check
      - run: cargo clippy --features hyper,axum -- -Dwarnings && cargo test --features hyper,axum
      - run: cargo clippy --all-features -- -Dwarnings && cargo test --all-features
      - run: cargo check --no-default-features --features hyper
      - run: cargo check --no-default-features --features axum
